Prevent /etc/init.d/restore from running on shutdown
And properly clean it up

diff --git a/roles/conduit/templates/restore.init.j2 b/roles/conduit/templates/restore.init.j2
--- a/roles/conduit/templates/restore.init.j2
+++ b/roles/conduit/templates/restore.init.j2
@@ -8,15 +8,17 @@
 # Description:       Finish recovery after reflash
 ### END INIT INFO
 
-echo "Updating opkg database"
+test "${1}" -eq "start" || exit 0
+
+echo "${0}: Updating opkg database"
 opkg update
 
-echo "Removing packages we do not want"
+echo "${0}: Removing packages we do not want"
 opkg remove mosquitto lora-network-server lora-packet-forwarder
 
-echo "Installing required packages"
+echo "${0}: Installing required packages"
 opkg install {{ ansible_depends | join(' ') }} ntp ntp-utils libmpsse
 
-echo "Removing myself"
-rm "${0}"
+echo ${0}: "Removing myself"
+rm /etc/init.d/restore
 update-rc.d $(basename ${0}) remove
