Improve ttn-pkt-forwarder
Restart by binary name.
Generate from a template to allow restart delay to be configured.
Add status command, this seems to make Ansible happier
Add logging to figure out what's going on

Addresses issue https://github.com/IthacaThings/ttn-multitech-cm/issues/64

diff --git a/roles/conduit/templates/ttn-pkt-forwarder.j2 b/roles/conduit/templates/ttn-pkt-forwarder.j2
--- a/roles/conduit/templates/ttn-pkt-forwarder.j2
+++ b/roles/conduit/templates/ttn-pkt-forwarder.j2
@@ -10,6 +10,9 @@
 
 PATH=/bin:/sbin:/usr/bin:/usr/sbin
 
+# source function library
+. /etc/init.d/functions
+
 NAME="ttn-packet-forwarder"
 ENABLED="yes"
 
@@ -40,6 +43,12 @@ lora_mt_id="${lora_prefix}-LORA"
 lora_1_0_hw="${lora_prefix}-LORA-1.0"
 lora_1_5_h_hw="${lora_prefix}-LORA-1.5"
 
+progname=$(basename $0)
+
+do_log() {
+    logger -t ${progname} $*
+}
+
 read_card_info() {
     # product-id of first lora card
     lora_id=$(mts-io-sysfs show lora/product-id 2> /dev/null)
@@ -63,7 +72,7 @@ card_found() {
     fi
 }
 
-do_start() {
+find_binary() {
     read_card_info
 
     if ! card_found; then
@@ -89,6 +98,9 @@ do_start() {
 	    exit 1
 	fi
     fi
+}
+
+do_start() {
 
     case ${pkt_fwd} in
 	/opt/lora/*)
@@ -109,9 +121,10 @@ do_start() {
 
 do_stop() {
     echo -n "Stopping $NAME: "
-    start-stop-daemon --stop --quiet --oknodo --pidfile $pkt_fwd_pidfile --retry 5
+    start-stop-daemon --stop --verbose --oknodo \
+	-x $pkt_fwd --retry=QUIT/x20/KILL/5 && \
+	echo "OK" || echo "FAIL"
     rm -f $pkt_fwd_pidfile
-    echo "OK"
 }
 
 if [ "$ENABLED" != "yes" ]; then
@@ -119,23 +132,40 @@ if [ "$ENABLED" != "yes" ]; then
     exit
 fi
 
+# Find which executable we use
+find_binary
+
+do_log "Running with '${*}' on binary ${pkt_fwd}"
+
 case "$1" in
     "start")
         do_start
+	rc=$?
         ;;
     "stop")
         do_stop
+	rc=$?
         ;;
     "restart")
         ## Stop the service and regardless of whether it was
         ## running or not, start it again.
         do_stop
-	sleep 5
+	# Ensure the interface has time to reset
+	sleep {{ forwarder_restart_delay }}
         do_start
+	rc=$?
         ;;
+    "status")
+	status ${pkt_fwd}
+	rc=$?
+	;;
     *)
         ## If no parameters are given, print which are avaiable.
         echo "Usage: $0 {start|stop|restart}"
         exit 1
         ;;
 esac
+
+do_log "Return ${rc}"
+
+exit ${rc}
